JUnit version 4.12
....I..E.EI.....
Time: 2.795
There were 2 failures:
1) test12(org.joda.time.LocalDateTime_ESTest)
org.evosuite.runtime.mock.java.lang.MockIllegalArgumentException: Invalid format: "2019-08-13T23:02:18.696" is malformed at "T23:02:18.696"
	at org.joda.time.format.DateTimeFormatter.parseLocalDateTime(DateTimeFormatter.java:825)
	at org.joda.time.LocalDateTime.parse(LocalDateTime.java:167)
	at org.joda.time.LocalDateTime_ESTest.test12(LocalDateTime_ESTest.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
2) test00(org.joda.time.LocalDateTime_ESTest)
org.evosuite.runtime.mock.java.lang.MockIllegalArgumentException: Invalid format: "F"
	at org.joda.time.format.DateTimeFormatter.parseLocalDateTime(DateTimeFormatter.java:825)
	at org.joda.time.LocalDateTime.parse(LocalDateTime.java:167)
	at org.joda.time.LocalDateTime_ESTest.test00(LocalDateTime_ESTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

FAILURES!!!
Tests run: 12,  Failures: 2

