JUnit version 4.12
.E.......E..E.E.E
Time: 4.928
There were 5 failures:
1) test09(com.google.javascript.rhino.head.NativeContinuation_ESTest)
com.google.javascript.rhino.head.EvaluatorException: Direct call is not supported
	at com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947)
	at com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:999)
	at com.google.javascript.rhino.head.NativeContinuation.construct(NativeContinuation.java:74)
	at com.google.javascript.rhino.head.NativeContinuation_ESTest.test09(NativeContinuation_ESTest.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
2) test10(com.google.javascript.rhino.head.NativeContinuation_ESTest)
java.lang.NullPointerException
	at com.google.javascript.rhino.head.ScriptRuntime.hasTopCall(ScriptRuntime.java:3108)
	at com.google.javascript.rhino.head.Interpreter.restartContinuation(Interpreter.java:894)
	at com.google.javascript.rhino.head.NativeContinuation.call(NativeContinuation.java:80)
	at com.google.javascript.rhino.head.NativeContinuation_ESTest.test10(NativeContinuation_ESTest.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
3) test04(com.google.javascript.rhino.head.NativeContinuation_ESTest)
org.evosuite.runtime.mock.java.lang.MockIllegalArgumentException: 8
	at com.google.javascript.rhino.head.NativeContinuation.initPrototypeId(NativeContinuation.java:98)
	at com.google.javascript.rhino.head.NativeContinuation_ESTest.test04(NativeContinuation_ESTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
4) test03(com.google.javascript.rhino.head.NativeContinuation_ESTest)
org.evosuite.runtime.mock.java.lang.MockIllegalArgumentException: BAD FUNCTION ID=110 MASTER=com.google.javascript.rhino.head.NativeContinuation@1
	at com.google.javascript.rhino.head.IdFunctionObject.unknown(IdFunctionObject.java:186)
	at com.google.javascript.rhino.head.IdScriptableObject.execIdCall(IdScriptableObject.java:600)
	at com.google.javascript.rhino.head.NativeContinuation.execIdCall(NativeContinuation.java:108)
	at com.google.javascript.rhino.head.NativeContinuation_ESTest.test03(NativeContinuation_ESTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
5) test02(com.google.javascript.rhino.head.NativeContinuation_ESTest)
com.google.javascript.rhino.head.EvaluatorException: Cannot modify a property of a sealed object: Continuation.
	at com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947)
	at com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:999)
	at com.google.javascript.rhino.head.Context.reportRuntimeError1(Context.java:962)
	at com.google.javascript.rhino.head.ScriptableObject.checkNotSealed(ScriptableObject.java:2193)
	at com.google.javascript.rhino.head.ScriptableObject.defineProperty(ScriptableObject.java:1557)
	at com.google.javascript.rhino.head.ScriptableObject.defineProperty(ScriptableObject.java:1577)
	at com.google.javascript.rhino.head.IdFunctionObject.addAsProperty(IdFunctionObject.java:103)
	at com.google.javascript.rhino.head.IdFunctionObject.exportAsScopeProperty(IdFunctionObject.java:109)
	at com.google.javascript.rhino.head.IdScriptableObject.exportAsJSClass(IdScriptableObject.java:622)
	at com.google.javascript.rhino.head.NativeContinuation_ESTest.test02(NativeContinuation_ESTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

FAILURES!!!
Tests run: 12,  Failures: 5

