entry: sources/closure-16/build/classes
entry: sources/closure-16/lib/args4j.jar
entry: sources/closure-16/lib/guava.jar
entry: sources/closure-16/lib/json.jar
entry: sources/closure-16/lib/jsr305.jar
entry: sources/closure-16/lib/protobuf-java.jar
entry: sources/closure-16/build/lib/rhino.jar
entry: sources/closure-16/lib/ant.jar
** CP: sources/closure-16/build/classes:sources/closure-16/lib/args4j.jar:sources/closure-16/lib/guava.jar:sources/closure-16/lib/json.jar:sources/closure-16/lib/jsr305.jar:sources/closure-16/lib/protobuf-java.jar:sources/closure-16/build/lib/rhino.jar:sources/closure-16/lib/ant.jar
* EvoSuite 1.0.7-SNAPSHOT
* Going to generate test cases for class: com.google.javascript.rhino.head.tools.shell.Global
* Starting Client-0
* Connecting to master process on port 18396
* Analyzing classpath: 
  - sources/closure-16/build/classes
  - sources/closure-16/lib/args4j.jar
  - sources/closure-16/lib/guava.jar
  - sources/closure-16/lib/json.jar
  - sources/closure-16/lib/jsr305.jar
  - sources/closure-16/lib/protobuf-java.jar
  - sources/closure-16/build/lib/rhino.jar
  - sources/closure-16/lib/ant.jar
* Finished analyzing classpath
* Generating tests for class com.google.javascript.rhino.head.tools.shell.Global
* Test criterion:
  - Branch Coverage
* Total number of test goals for DYNAMOSA: 320
* Using seed 1566407594558
* Starting evolution
* Initialsss Number of Goals in DynMOSA = 94 / 320
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.0875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.096875
[MASTER] 19:14:11.943 [logback-1] WARN  TestUsageChecker - class com.google.javascript.rhino.head.ContextFactory$1GlobalSetterImpl looks like an anonymous class, ignoring it (although reflection says false) GlobalSetterImpl
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.125
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.228125
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.30625
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.35
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.375
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.390625
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.396875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.41875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.43125
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.446875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.446875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.446875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.446875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.446875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.45
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.45
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.45
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.45
* Search finished after 312s and 156 generations, 50360 statements, best individual has fitness: 176.0
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.45
* Minimizing test suite
* Going to analyze the coverage criteria
* Coverage analysis for criterion BRANCH
* Coverage of criterion BRANCH: 44%
* Total number of goals: 320
* Number of covered goals: 141
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.45
* Generated 59 tests with total length 239
* Resulting test suite's coverage: 45%
* Generating assertions
* Resulting test suite's mutation score: 20%
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.45
* Compiling and checking tests
[MASTER] 19:19:33.222 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947): org.evosuite.runtime.mock.java.lang.MockThrowable: Class "null" not found.
[MASTER] 19:19:33.222 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Object[] objectArray0 = new Object[2];
Global.defineClass(context0, (Scriptable) nativeJavaClass0, objectArray0, (Function) nativeJavaClass0);

[MASTER] 19:19:35.662 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class org.evosuite.runtime.mock.java.lang.MockRuntimeException: No Context associated with current Thread
[MASTER] 19:19:35.662 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = new Context();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Global global0 = new Global(context0);
global0.runDoctest(context0, nativeJavaClass0, "js>js>m0yvu+", "error reporter", (-65954700));

[MASTER] 19:19:39.141 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.readUrl(Global.java:845): java.lang.NullPointerException
[MASTER] 19:19:39.141 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Global.readUrl(context0, nativeJavaClass0, context0.emptyArgs, nativeJavaClass0);

[MASTER] 19:19:45.131 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class org.evosuite.runtime.mock.java.lang.MockRuntimeException: No Context associated with current Thread
[MASTER] 19:19:45.132 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = new Context();
Global global0 = new Global(context0);
TopLevel.Builtins topLevel_Builtins0 = TopLevel.Builtins.RegExp;
BaseFunction baseFunction0 = global0.getBuiltinCtor(topLevel_Builtins0);
Object[] objectArray0 = new Object[8];
Object object0 = Global.print(context0, (Scriptable) null, objectArray0, baseFunction0);
assertNotNull(object0);


[MASTER] 19:19:45.841 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class org.evosuite.runtime.mock.java.lang.MockRuntimeException: No Context associated with current Thread
[MASTER] 19:19:45.841 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = new Context();
Global global0 = new Global(context0);
TopLevel.Builtins topLevel_Builtins0 = TopLevel.Builtins.Array;
BaseFunction baseFunction0 = global0.getBuiltinCtor(topLevel_Builtins0);
Global.quit(context0, baseFunction0, context0.emptyArgs, baseFunction0);
assertFalse(baseFunction0.isSealed());


[MASTER] 19:19:46.538 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:46.538 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
double double0 = Global.version(context0, nativeJavaClass0, context0.emptyArgs, nativeJavaClass0);
assertEquals(0.0, double0, 0.01);


[MASTER] 19:19:47.239 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:47.239 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeContinuation nativeContinuation0 = new NativeContinuation();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Object[] objectArray0 = new Object[2];
double double0 = Global.version(context0, nativeContinuation0, objectArray0, nativeJavaClass0);
assertEquals(0.0, double0, 0.01);


[MASTER] 19:19:47.868 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:47.869 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = new Context();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Global global0 = new Global();
Global.load(context0, global0, context0.emptyArgs, nativeJavaClass0);
assertTrue(global0.isExtensible());


[MASTER] 19:19:48.461 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportError(Context.java:905): org.evosuite.runtime.mock.java.lang.MockThrowable: Couldn't read source file "null": null.
[MASTER] 19:19:48.462 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeContinuation nativeContinuation0 = new NativeContinuation();
Object[] objectArray0 = new Object[2];
Global.load(context0, nativeContinuation0, objectArray0, nativeContinuation0);

[MASTER] 19:19:49.064 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.getClass(Global.java:338): java.lang.NullPointerException
[MASTER] 19:19:49.064 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
Delegator delegator0 = new Delegator();
Global.loadClass(context0, delegator0, context0.emptyArgs, delegator0);

[MASTER] 19:19:50.842 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.serialize(Global.java:360): java.lang.NullPointerException
[MASTER] 19:19:50.842 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Global global0 = new Global();
Context context0 = new Context();
NativeContinuation nativeContinuation0 = new NativeContinuation();
Global.serialize(context0, global0, context0.emptyArgs, nativeContinuation0);

[MASTER] 19:19:52.228 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.deserialize(Global.java:378): java.lang.NullPointerException
[MASTER] 19:19:52.228 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.enter();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Global.deserialize(context0, nativeJavaClass0, context0.emptyArgs, nativeJavaClass0);

[MASTER] 19:19:54.921 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:54.922 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeContinuation nativeContinuation0 = new NativeContinuation();
Object object0 = Global.doctest(context0, nativeContinuation0, context0.emptyArgs, nativeContinuation0);
assertEquals(false, object0);


[MASTER] 19:19:57.299 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.spawn(Global.java:574): java.lang.NullPointerException
[MASTER] 19:19:57.299 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.enter();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Global.spawn(context0, nativeJavaClass0, context0.emptyArgs, nativeJavaClass0);

[MASTER] 19:19:58.075 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947): org.evosuite.runtime.mock.java.lang.MockThrowable: Argument to spawn() must be a function or script.
[MASTER] 19:19:58.075 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Object[] objectArray0 = new Object[2];
Global.spawn(context0, nativeJavaClass0, objectArray0, nativeJavaClass0);

[MASTER] 19:19:58.828 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:58.828 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Object[] objectArray0 = new Object[1];
objectArray0[0] = (Object) nativeJavaClass0;
MockThread mockThread0 = (MockThread)Global.spawn(context0, nativeJavaClass0, objectArray0, nativeJavaClass0);
assertEquals(0, mockThread0.countStackFrames());


[MASTER] 19:20:00.093 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:20:00.093 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeContinuation nativeContinuation0 = new NativeContinuation();
Object[] objectArray0 = new Object[9];
objectArray0[0] = (Object) nativeContinuation0;
MockThread mockThread0 = (MockThread)Global.spawn(context0, nativeContinuation0, objectArray0, nativeContinuation0);
assertEquals(0, mockThread0.countStackFrames());


[MASTER] 19:20:00.845 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:20:00.845 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeContinuation nativeContinuation0 = new NativeContinuation();
Object[] objectArray0 = new Object[9];
objectArray0[0] = (Object) nativeContinuation0;
objectArray0[1] = (Object) nativeContinuation0;
MockThread mockThread0 = (MockThread)Global.spawn(context0, nativeContinuation0, objectArray0, nativeContinuation0);
assertEquals(0, mockThread0.countStackFrames());


[MASTER] 19:20:01.748 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.tools.ToolErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.sync(Global.java:616): java.lang.NullPointerException
[MASTER] 19:20:01.748 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
Delegator delegator0 = new Delegator();
Global.sync(context0, delegator0, context0.emptyArgs, delegator0);

[MASTER] 19:20:05.954 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.runCommand(Global.java:667): java.lang.NullPointerException
[MASTER] 19:20:05.955 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = new Context();
NativeContinuation nativeContinuation0 = new NativeContinuation();
Global.runCommand(context0, nativeContinuation0, context0.emptyArgs, nativeContinuation0);

[MASTER] 19:20:08.127 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947): org.evosuite.runtime.mock.java.lang.MockThrowable: The first argument to runCommand must be a command name.
[MASTER] 19:20:08.127 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = new Context();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
NativeArray nativeArray0 = new NativeArray(0L);
Global global0 = new Global();
Require require0 = global0.installRequire(context0, nativeArray0, false);
Object[] objectArray0 = new Object[1];
objectArray0[0] = (Object) require0;
Global.runCommand(context0, global0, objectArray0, nativeJavaClass0);

[MASTER] 19:20:09.677 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947): org.evosuite.runtime.mock.java.lang.MockThrowable: seal function can only be applied to objects
[MASTER] 19:20:09.677 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeContinuation nativeContinuation0 = new NativeContinuation();
Object[] objectArray0 = new Object[3];
objectArray0[0] = (Object) nativeContinuation0;
Global.seal(context0, nativeContinuation0, objectArray0, nativeContinuation0);

[MASTER] 19:20:10.343 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947): org.evosuite.runtime.mock.java.lang.MockThrowable: seal function supports only sealing of ScriptableObject instances
[MASTER] 19:20:10.344 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Object[] objectArray0 = new Object[1];
objectArray0[0] = (Object) nativeJavaClass0;
Global.seal(context0, nativeJavaClass0, objectArray0, nativeJavaClass0);

[MASTER] 19:20:11.650 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.readFile(Global.java:815): java.lang.NullPointerException
[MASTER] 19:20:11.650 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = new Context();
NativeJavaClass nativeJavaClass0 = new NativeJavaClass();
Global.readFile(context0, nativeJavaClass0, context0.emptyArgs, nativeJavaClass0);

[MASTER] 19:20:14.553 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:20:14.554 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Global global0 = new Global();
NativeContinuation nativeContinuation0 = new NativeContinuation();
Context context0 = new Context();
Object object0 = Global.toint32(context0, global0, context0.emptyArgs, nativeContinuation0);
assertEquals(0, object0);


* Permissions denied during test execution: 
  - java.lang.RuntimePermission: 
         writeFileDescriptor: 13
* Writing tests to file
* Writing JUnit test case 'Global_ESTest' to results/evosuite5/closure-16-com.google.javascript.rhino.head.tools.shell.Global-17
* Done!

* Computation finished
