entry: sources/closure-16/build/classes
entry: sources/closure-16/lib/args4j.jar
entry: sources/closure-16/lib/guava.jar
entry: sources/closure-16/lib/json.jar
entry: sources/closure-16/lib/jsr305.jar
entry: sources/closure-16/lib/protobuf-java.jar
entry: sources/closure-16/build/lib/rhino.jar
entry: sources/closure-16/lib/ant.jar
** CP: sources/closure-16/build/classes:sources/closure-16/lib/args4j.jar:sources/closure-16/lib/guava.jar:sources/closure-16/lib/json.jar:sources/closure-16/lib/jsr305.jar:sources/closure-16/lib/protobuf-java.jar:sources/closure-16/build/lib/rhino.jar:sources/closure-16/lib/ant.jar
* EvoSuite 1.0.7-SNAPSHOT
* Going to generate test cases for class: com.google.javascript.rhino.head.tools.shell.Global
* Starting Client-0
* Connecting to master process on port 13744
* Analyzing classpath: 
  - sources/closure-16/build/classes
  - sources/closure-16/lib/args4j.jar
  - sources/closure-16/lib/guava.jar
  - sources/closure-16/lib/json.jar
  - sources/closure-16/lib/jsr305.jar
  - sources/closure-16/lib/protobuf-java.jar
  - sources/closure-16/build/lib/rhino.jar
  - sources/closure-16/lib/ant.jar
* Finished analyzing classpath
* Generating tests for class com.google.javascript.rhino.head.tools.shell.Global
* Test criterion:
  - Branch Coverage
* Total number of test goals for DYNAMOSA: 320
* Using seed 1566407553048
* Starting evolution
* Initialsss Number of Goals in DynMOSA = 94 / 320
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.084375
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.10625
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.203125
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.321875
[MASTER] 19:13:51.866 [logback-1] WARN  TestUsageChecker - class com.google.javascript.rhino.head.ContextFactory$1GlobalSetterImpl looks like an anonymous class, ignoring it (although reflection says false) GlobalSetterImpl
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.353125
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.390625
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.425
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.425
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.425
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.425
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.44375
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.44375
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.4625
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.471875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.471875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.4875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.4875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.4875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.4875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.4875
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.4875
* Search finished after 302s and 191 generations, 62967 statements, best individual has fitness: 164.0
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.4875
* Minimizing test suite
* Going to analyze the coverage criteria
* Coverage analysis for criterion BRANCH
* Coverage of criterion BRANCH: 48%
* Total number of goals: 320
* Number of covered goals: 155
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.4875
* Generated 60 tests with total length 215
* Resulting test suite's coverage: 49%
* Generating assertions
* Resulting test suite's mutation score: 27%
Current fitness function value: class org.evosuite.coverage.branch.BranchCoverageSuiteFitness ** 0.4875
* Compiling and checking tests
[MASTER] 19:19:19.099 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class org.evosuite.runtime.mock.java.lang.MockRuntimeException: No Context associated with current Thread
[MASTER] 19:19:19.100 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = new Context();
Global global0 = new Global(context0);
Delegator delegator0 = new Delegator(global0);
Global.help(context0, global0, context0.emptyArgs, delegator0);

[MASTER] 19:19:20.348 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947): org.evosuite.runtime.mock.java.lang.MockThrowable: doctest failure running:
~V<}^`wnl+U/E``!
expected: actual: js: "doctest input", line 1: syntax error
js: ~V<}^`wnl+U/E``!
js: ...^
js: "doctest input", line 1: illegal character
js: ~V<}^`wnl+U/E``!
js: .....^
js: "doctest input", line 1: illegal character
js: ~V<}^`wnl+U/E``!
js: .............^
js: "doctest input", line 1: Compilation produced 3 syntax errors.



[MASTER] 19:19:20.348 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Global global0 = new Global();
Context context0 = new Context();
global0.runDoctest(context0, (Scriptable) null, "js>~V<}^`wnl+U/E``!", "error reporter", 11);

[MASTER] 19:19:24.534 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947): org.evosuite.runtime.mock.java.lang.MockThrowable: The first argument to runCommand must be a command name.
[MASTER] 19:19:24.534 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Global global0 = new Global();
Object[] objectArray0 = new Object[1];
objectArray0[0] = (Object) global0;
IdFunctionObject idFunctionObject0 = new IdFunctionObject(global0, (Object) null, 1, 1);
Global.runCommand((Context) null, global0, objectArray0, idFunctionObject0);

[MASTER] 19:19:30.851 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:30.851 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
double double0 = Global.version(context0, (Scriptable) null, context0.emptyArgs, (Function) null);
assertEquals(0.0, double0, 0.01);


[MASTER] 19:19:32.554 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:32.554 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
Global.load(context0, (Scriptable) null, context0.emptyArgs, (Function) null);
assertEquals((-1), Context.VERSION_UNKNOWN);


[MASTER] 19:19:33.375 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportError(Context.java:905): org.evosuite.runtime.mock.java.lang.MockThrowable: Couldn't read source file "null": null.
[MASTER] 19:19:33.376 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Global global0 = new Global();
Object[] objectArray0 = new Object[3];
Global.load((Context) null, global0, objectArray0, (Function) null);

[MASTER] 19:19:34.251 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947): org.evosuite.runtime.mock.java.lang.MockThrowable: Class "null" not found.
[MASTER] 19:19:34.252 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Global global0 = new Global();
IdFunctionObject idFunctionObject0 = global0.exportAsJSClass(8, global0, false);
Object[] objectArray0 = new Object[2];
Global.defineClass((Context) null, (Scriptable) idFunctionObject0, objectArray0, (Function) idFunctionObject0);

[MASTER] 19:19:35.115 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.getClass(Global.java:338): java.lang.NullPointerException
[MASTER] 19:19:35.116 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
Global.loadClass(context0, (Scriptable) null, context0.emptyArgs, (Function) null);

[MASTER] 19:19:36.640 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.serialize(Global.java:360): java.lang.NullPointerException
[MASTER] 19:19:36.640 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Delegator delegator0 = new Delegator();
Context context0 = Context.enter();
Global.serialize(context0, delegator0, context0.emptyArgs, delegator0);

[MASTER] 19:19:38.292 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.deserialize(Global.java:378): java.lang.NullPointerException
[MASTER] 19:19:38.292 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Global global0 = new Global();
Context context0 = Context.enter();
Global.deserialize(context0, global0, context0.emptyArgs, (Function) null);

[MASTER] 19:19:41.393 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:41.394 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
Object object0 = Global.doctest(context0, (Scriptable) null, context0.emptyArgs, (Function) null);
assertEquals(false, object0);


[MASTER] 19:19:43.277 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.spawn(Global.java:574): java.lang.NullPointerException
[MASTER] 19:19:43.277 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
NativeContinuation nativeContinuation0 = new NativeContinuation();
Global.spawn(context0, nativeContinuation0, context0.emptyArgs, nativeContinuation0);

[MASTER] 19:19:44.006 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.Context.reportRuntimeError(Context.java:947): org.evosuite.runtime.mock.java.lang.MockThrowable: Argument to spawn() must be a function or script.
[MASTER] 19:19:44.006 [logback-1] WARN  JUnitAnalyzer - Failing test:
 BaseFunction baseFunction0 = new BaseFunction();
Context context0 = Context.getCurrentContext();
Object[] objectArray0 = new Object[11];
Global.spawn(context0, baseFunction0, objectArray0, baseFunction0);

[MASTER] 19:19:44.674 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:44.675 [logback-1] WARN  JUnitAnalyzer - Failing test:
 BaseFunction baseFunction0 = new BaseFunction();
Context context0 = Context.getCurrentContext();
Object[] objectArray0 = new Object[11];
objectArray0[0] = (Object) baseFunction0;
MockThread mockThread0 = (MockThread)Global.spawn(context0, baseFunction0, objectArray0, baseFunction0);
assertEquals(0, mockThread0.countStackFrames());


[MASTER] 19:19:46.044 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:46.044 [logback-1] WARN  JUnitAnalyzer - Failing test:
 BaseFunction baseFunction0 = new BaseFunction();
Context context0 = Context.getCurrentContext();
Object[] objectArray0 = new Object[5];
objectArray0[0] = (Object) baseFunction0;
objectArray0[1] = (Object) baseFunction0;
MockThread mockThread0 = (MockThread)Global.spawn(context0, baseFunction0, objectArray0, baseFunction0);
assertFalse(mockThread0.isInterrupted());


[MASTER] 19:19:46.894 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.tools.ToolErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.sync(Global.java:616): java.lang.NullPointerException
[MASTER] 19:19:46.894 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.enter();
BaseFunction baseFunction0 = new BaseFunction();
Global.sync(context0, baseFunction0, context0.emptyArgs, baseFunction0);

[MASTER] 19:19:49.583 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.runCommand(Global.java:667): java.lang.NullPointerException
[MASTER] 19:19:49.583 [logback-1] WARN  JUnitAnalyzer - Failing test:
 BaseFunction baseFunction0 = new BaseFunction();
Context context0 = Context.getCurrentContext();
Global.runCommand(context0, baseFunction0, context0.emptyArgs, baseFunction0);

[MASTER] 19:19:54.343 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.readFile(Global.java:815): java.lang.NullPointerException
[MASTER] 19:19:54.343 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = new Context();
BaseFunction baseFunction0 = new BaseFunction();
Global.readFile(context0, baseFunction0, context0.emptyArgs, baseFunction0);

[MASTER] 19:19:56.304 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.AssertionError: Exception was not thrown in com.google.javascript.rhino.head.DefaultErrorReporter but in com.google.javascript.rhino.head.tools.shell.Global.readUrl(Global.java:845): java.lang.NullPointerException
[MASTER] 19:19:56.304 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = Context.getCurrentContext();
Global.readUrl(context0, (Scriptable) null, context0.emptyArgs, (Function) null);

[MASTER] 19:19:57.684 [logback-1] WARN  JUnitAnalyzer - Found unstable test named test0 -> class java.lang.NullPointerException: null
[MASTER] 19:19:57.684 [logback-1] WARN  JUnitAnalyzer - Failing test:
 Context context0 = new Context();
NativeContinuation nativeContinuation0 = new NativeContinuation();
Object object0 = Global.toint32(context0, nativeContinuation0, context0.emptyArgs, nativeContinuation0);
assertEquals(0, object0);


* Permissions denied during test execution: 
  - java.lang.RuntimePermission: 
         writeFileDescriptor: 12
* Writing tests to file
* Writing JUnit test case 'Global_ESTest' to results/evosuite5/closure-16-com.google.javascript.rhino.head.tools.shell.Global-11
* Done!

* Computation finished
