JUnit version 4.12
.E...........................I.......I.......E......E...
Time: 1.96
There were 3 failures:
1) test20(org.mockito.asm.util.ASMifierClassVisitor_ESTest)
org.evosuite.runtime.mock.java.io.MockIOException: Class not found
	at org.mockito.asm.ClassReader.readClass(ClassReader.java:382)
	at org.mockito.asm.ClassReader.<init>(ClassReader.java:359)
	at org.mockito.asm.ClassReader.<init>(ClassReader.java:369)
	at org.mockito.asm.util.ASMifierClassVisitor.main(ASMifierClassVisitor.java:188)
	at org.mockito.asm.util.ASMifierClassVisitor_ESTest.test20(ASMifierClassVisitor_ESTest.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
2) test13(org.mockito.asm.util.ASMifierClassVisitor_ESTest)
org.evosuite.runtime.mock.java.io.MockIOException: Class not found
	at org.mockito.asm.ClassReader.readClass(ClassReader.java:382)
	at org.mockito.asm.ClassReader.<init>(ClassReader.java:359)
	at org.mockito.asm.ClassReader.<init>(ClassReader.java:369)
	at org.mockito.asm.util.ASMifierClassVisitor.main(ASMifierClassVisitor.java:188)
	at org.mockito.asm.util.ASMifierClassVisitor_ESTest.test13(ASMifierClassVisitor_ESTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
3) test19(org.mockito.asm.util.ASMifierClassVisitor_ESTest)
org.evosuite.runtime.mock.java.io.MockIOException: Class not found
	at org.mockito.asm.ClassReader.readClass(ClassReader.java:382)
	at org.mockito.asm.ClassReader.<init>(ClassReader.java:359)
	at org.mockito.asm.ClassReader.<init>(ClassReader.java:369)
	at org.mockito.asm.util.ASMifierClassVisitor.main(ASMifierClassVisitor.java:188)
	at org.mockito.asm.util.ASMifierClassVisitor_ESTest.test19(ASMifierClassVisitor_ESTest.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

FAILURES!!!
Tests run: 51,  Failures: 3

